database:
  connection_string: postgres://username@localhost/database_name OR jdbc:postgresql://localhost/database_name?user=username
log_level: info
database_log_level: error
quandl:
  api_key: abc123
  api_version: "2015-04-09"
